PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS FinNews (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, text TEXT NOT NULL, url TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS Rates (id INTEGER PRIMARY KEY AUTOINCREMENT, rate_text TEXT NOT NULL, rate_symbol TEXT NOT NULL, sum_rub TEXT NOT NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
